  <div class="page-title">
    <h2><?php echo $this->__('My Dashboard') ?></h2>
  </div> <!--page-title-->
<!-- BEGIN DASHBOARD-->
<div class="dashboard">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('hello') ?>
    <?php echo $this->getChildHtml('top') ?>
    <div class="box-account">
        <div class="page-title">
            <h2><?php echo $this->__('Account Information') ?></h2>
        </div>
        <?php /* Extensions placeholder */ ?>
        <?php echo $this->getChildHtml('customer.account.dashboard.extra') ?>
        <?php echo $this->getChildHtml('info') ?>
        <?php echo $this->getChildHtml('address') ?>
    </div>
    <?php echo $this->getChildHtml('info1') ?>
    <?php echo $this->getChildHtml('info2') ?>
</div>
