
<div class="block block-account">
    <div class="block-title">
        <?php echo $this->__('My Account'); ?>
    </div>
    <div class="block-content">
        <ul>
            <?php $_links = $this->getLinks(); ?>
            <?php $_index = 1; ?>
            <?php $_count = count($_links); ?>
            <?php foreach ($_links as $_link): ?>
                <?php $_last = ($_index++ >= $_count); ?>
                <?php if ($this->isActive($_link)): ?>
                    <li class="current<?php echo ($_last ? ' last' : '') ?>"><a><?php echo $_link->getLabel() ?></a></li>
                <?php else: ?>
                    <li<?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><span> <?php echo $_link->getLabel() ?></span></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div> <!--block-content-->
</div> <!--block block-account-->
