
<?php /* @var $this Mage_Sales_Block_Recurring_Profiles */ ?>

<div class="page-title">
    <h2><?php echo $this->__('Recurring Profiles') ?></h2>
</div>
<div class="line"></div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="login_page">
<div class="recurring-profiles login_page">

    <?php echo $this->getChildHtml('grid')?>

    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeHtml($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    </div>
</div>
</div> <!--login_page-->
