<?php
	$home_url = Mage::helper('core/url')->getHomeUrl();

?>

<div id="main" class="wrapper">
	<?php
		echo $this->getChildHtml('blog_right');
	?>
	<?php //echo $this->getPagerHtml(); ?>
	<div id="primary" class="site-content">
		<div id="content" role="main">
			<?php
			$processor = Mage::getModel('core/email_template_filter');
			$all_post_collection = $this->getCollection();//$this->getAllPost();
			$home_url = Mage::helper('core/url')->getHomeUrl();
			$post_count = 0;

			$blogmate_config = Mage::getStoreConfig('blogmate');
			// print_r($blogmate_config);

			foreach ($all_post_collection as $post_key => $post_value) {
				++$post_count;
				//$blog_url = $home_url.'blog/view/post/p/'.$post_value['title_slug'].'/';

				$urlKey = $post_value['title_slug'];
				    $curl = Mage::getUrl('blog/view/post/p/'.$urlKey, array('_direct' => $urlKey)); 
				    $cnt=Mage::getModel('blogmate/blog')->chkIfExists('index/'.$urlKey,$urlKey);
				    $store_id=Mage::app()->getStore()->getId();
				    if($cnt==0 && ($urlKey !=''))
				    {	
					    $curl1=$post_value['title_slug'];
					    $rewrite = Mage::getModel('core/url_rewrite');
					    $rewrite->setStoreId($store_id)
					    ->setIdPath('index/'.$urlKey)
					    ->setRequestPath($curl1)
					    ->setTargetPath('blog/view/post/p/'.$urlKey)
					    ->setIsSystem(true)
					    ->save();

				    }
				    $blog_url =$curl; 
				?>
				<article id="post-29" class="post-29 post type-post status-publish format-standard hentry category-daytrips">
					<header class="entry-header">
						<h1 class="entry-title">
							<a href="<?php echo $blog_url;?>" rel="bookmark"><?php echo $title = $processor->filter($post_value['title']);?></a>
						</h1>
					</header>
					<div class="entry-content">
						<?php echo $short_blog_content = $processor->filter($post_value['short_blog_content']);?>
						<p>
							<a href="<?php echo $blog_url;?>" class="more-link"><?php echo $this->__('Continue reading') ?> <span class="meta-nav">→</span></a>
						</p>
					</div>
               <script>
               jQuery(window).load(function(){
                  jQuery('.entry-content img:first-of-type').click(function(){
                     window.location.href ="<?php echo $blog_url;?>";
                  });
               });
               </script>
				</article>
				<?php
			}
			if($post_count == 0) {
				?>
				<article id="post-29" class="post-29 post type-post status-publish format-standard hentry category-daytrips">
					<div class="entry-content">
                  <?php echo $this->__('There are no posts under this category.') ?>
					</div>
				</article>
				<?php
			}
			?>
		</div>
	</div>

</div>
