<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Raf
 * @version    2.1.5
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if (!Mage::getSingleton('customer/session')->isLoggedIn() || !Mage::helper('awraf/config')->isInviteAllowed()): return; endif?>
<?php
$buttonId = uniqid( rand(0, 1000) );
?>
<button class="button" id="referafriend-button<?php echo $buttonId;?>" type="button"><?php echo $this->__('Invite a Friend and get Discount') ?></button>
<script type="text/javascript">
    //<![CDATA[
    document.observe('dom:loaded', function () {
        if ($('raf-invite')) {
            Quo($('referafriend-button<?php echo $buttonId;?>')).tap(function(e){
                window.rafInvitePopup = new awMobile2.app.popup();
                window.rafInvitePopup.open($('raf-invite'), <?php echo Zend_Json::encode($this->__('Refer a Friend'));?>, <?php echo Zend_Json::encode($this->__('Cancel'));?>, function() {}, false);
            });
        }
    });
    //]]>
</script>