<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Raf
 * @version    2.1.5
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="aw-raf-statistics">
    <div class="raf-balance">
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <h3 class="raf-section__title"><?php echo $this->__('Active Balance'); ?></h3>
        <div class="raf-section__content">
            <?php echo $this->getActiveBalance(); ?>
        </div>
        <h3 class="raf-section__title"><?php echo $this->__('Active Discount'); ?></h3>
        <div class="raf-section__content">
            <?php echo (float) $this->getActiveDiscount(); ?>%
        </div>
    </div>
    <div class="islands">
        <?php if ($this->isInviteAllowed()): ?>
        <div class="island">
            <?php echo $this->getChildHtml('awraf.invite_button'); ?>
        </div>
        <div class="island">
            <h3 class="raf-section__title"><?php echo $this->__('Share broadcast link'); ?></h3>
            <?php echo $this->getChildHtml('awraf.broad.cast.link'); ?>
        </div>
        <?php endif; ?>
    </div>
</div>