<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Raf
 * @version    2.1.5
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="aw-raf-statistics">
    <div class="awraf-social-share">
        <a class="raf-twitter-share" href="<?php echo $this->getTwitterUrl();?>" title="<?php echo $this->__('Share on Twitter'); ?>"></a>
        <a class="raf-facebook-share" href="<?php echo $this->getFacebookUrl();?>" title="<?php echo $this->__('Share on Facebook'); ?>"></a>
        <a class="raf-myspace-share" href="<?php echo $this->getMyspaceUrl();?>" title="<?php echo $this->__('Share on MySpace'); ?>"></a>
    </div>
</div>
