<?php
$order = Mage::getModel('sales/order')->load(Mage::getSingleton('checkout/session')->getLastOrderId());
$items = $order->getAllItems();
$currency = Mage::app()->getStore()->getCurrentCurrencyCode();
$grand_total = round($order->getGrandTotal(), 2);
$shipping_cost = $order->getShippingAmount();
$coupon_code = Mage::getSingleton('checkout/session')->getQuote()->getCouponCode();
?>

<div class="page-title">
    <h2><?php echo $this->__('Your order has been received.') ?></h2>
</div>
<div class="line"></div>
<div class="dashboard">
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <h2 class="sub-title"><?php echo $this->__('Thank you for your purchase!') ?></h2>

<?php if ($this->getOrderId()): ?>
        <?php if ($this->getCanViewOrder()) : ?>
            <p><?php echo $this->__('Your order # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?></p>
        <?php else : ?>
            <p><?php echo $this->__('Your order # is: %s.', $this->escapeHtml($this->getOrderId())) ?></p>
        <?php endif; ?>
        <p><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
        <?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) : ?>
            <p>
            <?php echo $this->__('Click <a href="%s" onclick="this.target=\'_blank\'">here to print</a> a copy of your order confirmation.', $this->getPrintUrl()) ?>
                <?php echo $this->getChildHtml() ?>
            </p>
            <?php endif; ?>
    <?php endif; ?>

    <?php if ($this->getAgreementRefId()): ?>
        <p><?php echo $this->__('Your billing agreement # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId()))) ?></p>
    <?php endif; ?>

    <?php if ($profiles = $this->getRecurringProfiles()): ?>
        <p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
        <ul class="disc">
    <?php foreach ($profiles as $profile): ?>
                <?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id'))); ?>
                <li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($this->getObjectData($profile, 'schedule_description'))) ?></li>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>

    <div class="buttons-set">
        <button type="button" class="button continue" title="<?php echo $this->__('Continue Shopping') ?>" onclick="window.location = '<?php echo $this->getUrl() ?>'"><span><?php echo $this->__('Continue Shopping') ?></span></button>
    </div>
</div> <!--dashboard-->
<br />
