

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title">
    <h2><?php echo $this->__('My Tags') ?></h2>
</div>
<div class="line"></div>
<div class="login_page">
<div class="login-page">
<?php if($this->getTags()): ?>
    <p><?php echo $this->__('Click on a tag to view your corresponding products.') ?></p>
    <ul class="tags-list">
        <?php foreach ($this->getTags() as $_tag): ?>
            <li><a href="<?php echo $this->getUrl('tag/customer/view', array('tagId' => $_tag->getTagId())) ?>" style="font-size:<?php echo $_tag->getRatio()*70+75 ?>%;"><?php echo $this->htmlEscape($_tag->getName()) ?></a></li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <p><?php echo $this->__('You have not tagged any products yet.') ?></p>
<?php endif; ?>
<div class="buttons-set">
    <p class="back-link"><a class="button" href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
</div> <!--login-page-->
</div> <!--login_page-->