<div class="page-title">
    <h2><?php echo $this->__('My Tags') ?></h2>
</div>
<div class="line"></div>
<div class="login_page">
<div class="login-page">
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<p class="my-tag-edit">
    <a href="#" title="<?php echo $this->__('Delete') ?>" onclick="if(confirm('<?php echo $this->__('Are you sure you want to delete this tag?') ?>')) window.location='<?php echo $this->getTagInfo()->getRemoveTagUrl(); ?>'; return false;" class="button button-2x"><?php echo $this->__('Delete') ?></a>
    <?php echo $this->__('<strong>Tag Name:</strong> %s', $this->htmlEscape($this->getTagInfo()->getName())) ?>
</p>
<div class="clearer"></div>
<?php echo $this->getToolbarHtml() ?>
<table class="data-table" id="my-tags-table">
<?php if( sizeof($this->getMyProducts()) > 0 ): ?>
    <col width="1" />
    <col />
    <col width="1" />
    <tbody>
    <?php $iterator = 0 ?>
    <?php foreach($this->getMyProducts() as $_product): ?>
        <tr<?php if($iterator % 2 == 0): ?> class="odd"<?php $iterator++;endif; ?>>
            <td><a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(100, 100); ?>" width="100" height="100" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></a></td>
            <td>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h2>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php echo $this->getPriceHtml($_product) ?>
                <?php echo $this->htmlEscape($_product->getDescription()) ?>
            </td>
            <td>
                <?php if($_product->isSaleable()): ?>
                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button button-2x" onclick="setLocation('<?php echo $this->getUrl('checkout/cart/add',array('product'=>$_product->getId())) ?>')"><?php echo $this->__('Add to Cart') ?></button>
                <?php endif; ?>
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                <ul class="add-to-links">
                    <li>
                        <a href="<?php echo $this->getUrl('wishlist/index/add',array('product'=>$_product->getId())) ?>" class=""><?php echo $this->__('Add to Wishlist') ?></a>
                    </li>
                </ul>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
<?php else: ?>
    <tbody>
        <tr>
            <td>
                <?php echo $this->__("Unable to find any products tagged with '%s' in the current store", $this->htmlEscape($this->getTagInfo()->getName()) ) ?>
            </td>
        </tr>
    </tbody>
<?php endif; ?>
</table>
<script type="text/javascript">decorateTable('my-tags-table')</script>
<?php echo $this->getToolbarHtml() ?>
<div class="buttons-set">
    <p class="back-link"><a class="button button-2x" href="<?php echo $this->getUrl('*/*/')?>"><small>&laquo; </small><?php echo $this->__('Back to Tags List')?></a></p>
</div>
</div> <!--login-page-->
</div> <!--login_page-->
