<?php
/**
 * Toogas Lda.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA (End-User License Agreement)
 * that is bundled with this package in the file licence_toogas_community.txt.
 * It is also available at this URL:
 * http://www.toogas.com/licences/toogas_community.txt
 *
 * @category   Toogas
 * @package    Toogas_Toogaslda
 * @copyright  Copyright (c) 2010 Toogas Lda. (http://www.toogas.com)
 * @license    http://www.toogas.com/licences/toogas_community.txt
 */
 ?>
<style>
	.toogas-promo {
		background:#EAF0EE url(<?php echo $this->getSkinUrl('images/toogas/toogas_logo.jpg') ?>) no-repeat scroll 5px center;
		border:1px solid #CCCCCC;
		margin-bottom:10px;
		padding:10px 5px 5px 115px;
	}
	.toogas-promo h4, .toogas-promo p {
		margin:0;
	}
	.toogas-promo h2 {
		color:#444444;
		font-size:1.4em;
		line-height:1em;
	}
	.toogas-promo a {
		text-decoration:none;
	}
	
	.save {
		display: none;
	}	
</style>
<div class="toogas-promo">
    <h4><?php echo Mage::helper('toogaslda')->__('Contact Toogas')?></h4>
    <p><a href="http://www.toogas.com/contacts/"><?php echo Mage::helper('toogaslda')->__('Contact us!')?></a></p>
    <p>&nbsp</p>
    <p>&nbsp</p>
    <p>&nbsp</p>            
</div>