<div id="main" class="wrapper">
	<div id="primary">
		<div id="content" role="main">
			<?php
			$processor = Mage::getModel('core/email_template_filter');
			
			//$post_title_slug = $this->getRequest()->getParam('p');
			$currentUrl = Mage::helper('core/url')->getCurrentUrl();
			$post_title_slug = substr( $currentUrl, strrpos( $currentUrl, '/' )+1 );
			$post_data = $this->getPostDataBySlug($post_title_slug);
			$post_value = $post_data[0];

				?>
				<article id="post-29" class="post-29 post type-post status-publish format-standard hentry category-daytrips">
					<header class="entry-header">
						<h1 class="entry-title">
							<?php echo $title = $processor->filter($post_value['title']);?>
						</h1>
					</header>
					<div class="entry-content">
						<?php echo $blog_content = $processor->filter($post_value['blog_content']);?>
					</div>
				</article>
				<?php
			
			?>
			<div class="comment-content">
				<?php
					$comment_config = Mage::getStoreConfig('blogmate/comment_setting');
					if($comment_config['enabled'] && $post_value['enable_comment']) {
						echo $this->getChildHtml('blog_comments');

					}
				?>
			</div>
		</div>
	</div>

</div>
