  <div class="page-title">
    <h2><?php echo $this->__('Forgot Your Password?') ?></h2>
  </div> <!--page-title-->
<div class="line"></div>
<div class="login_page">
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
    <div class="col2-set">
    <strong><?php echo $this->__('Retrieve your password here') ?></strong>
      <div class="content">        
        <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
        <ul class="form-list">
            <li>
                <label for="email_address"><?php echo $this->__('Email Address') ?><em class="required">*</em></label>
                <div class="input-box">
                    <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
                </div>
            </li>
            <?php echo $this->getChildHtml('form.additional.info'); ?>
        </ul>
      </div>  <!--content-->
      
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <button  type="submit" title="<?php echo $this->__('Submit') ?>" class="button submit"><span><?php echo $this->__('Submit') ?></span></button>
        <a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a>
      
    </div>  <!--col2-set-->
</form>
</div>  <!--login_page-->

<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
