
<div class="page-title">
    <h2><?php echo $this->__('Newsletter Subscription') ?></h2>
</div>
<div class="line"></div>
<div class="dashboard">
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('form_before')?>
<form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Newsletter Subscription') ?></h2>
        <ul class="form-list" style="margin:0 0 5px;">
            <li class="control"><input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php echo $this->__('General Subscription') ?>"<?php if($this->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="subscription"><?php echo $this->__('General Subscription') ?></label></li>
            <?php /* Extensions placeholder */ ?>
            <?php echo $this->getChildHtml('customer.form.newsletter.extra')?>
        </ul>
    </div>
    <div class="buttons-set">
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><?php echo $this->__('Save') ?></span></button>
        <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" style="display: inline-block; border: 0; background: #1BBBB7; padding: 8px 12px; font-size: 14px; text-align: center; white-space: nowrap; color: #fff; font-weight: normal; transition: all 0.3s linear; -moz-transition: all 0.3s linear; -webkit-transition: all 0.3s linear; -webkit-border-radius: 2px; -moz-border-radius: 2px; border-radius: 2px; vertical-align: top; cursor: pointer; overflow: visible; width: auto; outline: none; -webkit-border-fit: lines;"><span>&laquo; <?php echo $this->__('Back') ?></span></a>
    </div>
</form>
</div> <!--dashboard-->
<?php /* Extensions placeholder */ ?>
<?php echo $this->getChildHtml('customer.form.newsletter.extra2')?>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>