<div class="dezireping-cart">
<div class="container top">
<div class="row">
 <div class="span12">
  <div class="wrapper">
    <h2 class="nopadding"><?php echo $this->__('Reset a Password'); ?></h1>
  </div> <!--wrapper-->
 </div> <!--span12-->
</div> <!--row-->
<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
<form action="<?php echo $this->getUrl('*/*/resetpasswordpost', array('_query' => array('id' => $this->getCustomerId(), 'token' => $this->getResetPasswordLinkToken()))); ?>" method="post" id="form-validate">
    <div class="fieldset" style="margin-top: 10px;">
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="password"><?php echo $this->__('New Password'); ?><em class="required">*</em></label>
                    <div class="input-box">
                        <input type="password" class="input-text required-entry validate-password" name="password" id="password" />
                    </div>
                </div>
                <div class="field">
                    <label for="confirmation"><?php echo $this->__('Confirm New Password'); ?><em class="required">*</em></label>
                    <div class="input-box">
                        <input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
    
        <p class="required"><?php echo $this->__('* Required Fields'); ?></p>
        <button type="submit" title="<?php echo $this->__('Reset a Password'); ?>" class="button button-2x"><?php echo $this->__('Reset a Password'); ?></button>
    
</form>
</div>  <!--container top-->
</div>  <!--dezireping-cart-->

<script type="text/javascript">
/*<![CDATA[*/
    var dataForm = new VarienForm('form-validate', true);
/*]]>*/
</script>
