<?php $config = Mage::getStoreConfig('deziresettings/deziresettings_appearance'); ?>

<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link href='https://fonts.googleapis.com/css?family=Quantico:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=<?php echo str_replace(' ', '+', $config['font']); ?>:200,300,400,500,600,700,800' rel='stylesheet' type='text/css'>
<!-- Midori Kocak -->
<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->
<script type="text/javascript">
var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
var SKIN_URL = '<?php echo $this->helper('core/js')->getJsSkinUrl('') ?>';
</script>
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>

<style type="text/css">
/*  update google Font  */
.page-title h1, .page-title h2,#nav > li > a,.totals h3,.crosssel h2,.cart-collaterals .col2-set h3,.block .block-title,.side-nav-categories .block-title,.block-account .block-title,.block-company .block-title,.product-view .product-name h1,.tab-box .activeLink a,.tab-box a,.tab-box a:hover,.one-page-checkout .step-title .number,.one-page-checkout .active .step-title h3,.one-page-checkout .step-title h3,.one-page-checkout .active .step-title,.page-title_multi h2,.login_page strong ,#store-messages .phone span,#store-messages .message span ,footer h4 ,.store-img-box .feature-box,.new_title h2 ,.related-block .block-title,.up-sell-slider .block-title,.popular-block .block-title,.orange-slider .text,#menu ul.navmenu .menutop h2{ font-family: 'Lato',  sans-serif;  }

/* update theme color */
.products-grid .actions button.button.btn-cart, .product-view .product-shop .add-to-box .btn-cart, .right-side-content button.button.btn-sent { background:<?php echo $config['color']; ?>; } 

<?php   if ( !empty($config['header_bg_color']) ) : ?>
header { background:<?php echo $config['header_bg_color']; ?> }
<?php endif; ?>
<?php if ( !empty($config['header_fg_color']) ) : ?>
.toplinks ul.links li a, .toplinks .links li .click-nav ul .clicker {color:<?php echo $config['header_fg_color']; ?>}
<?php endif; ?>
<?php if ( !empty($config['footer_bg_color']) ) : ?>
footer {background:<?php echo $config['footer_bg_color']; ?>}
<?php endif; ?>
<?php if ( !empty($config['footer_fg_color']) ) : ?>
footer h4 {color:<?php echo $config['footer_fg_color']; ?>}
<?php endif; ?>
<?php if ( !empty($config['content_bg_color']) ) : ?>
html {background:<?php echo $config['content_bg_color']; ?>}
<?php endif;  ?>
</style>