
<div class="col2-set">
    <div class="col-1">  
      <div class="box"> 
          <div class="box-title">     
                <h5><?php echo $this->__('Contact Information') ?></h5>
                <a href="<?php echo $this->getUrl('customer/account/edit') ?>"><?php echo $this->__('Edit') ?></a>                        
          </div>  <!--box-title-->
          <div class="box-content">
                <p>
                    <?php echo $this->htmlEscape($this->getCustomer()->getName()) ?><br />
                    <?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?><br />
                    <a href="<?php echo $this->getChangePasswordUrl() ?>"><?php echo $this->__('Change Password') ?></a>
                </p>  
          </div>  <!--box-content-->  
      </div>  <!--box-->                
    </div>
    <?php if( $this->isNewsletterEnabled() ): ?>
    <div class="col-2">   
      <div class="box"> 
          <div class="box-title">                
                <h5><?php echo $this->__('Newsletters') ?></h5>
                <a href="<?php echo $this->getUrl('newsletter/manage') ?>"><?php echo $this->__('Edit') ?></a>                      
          </div>  <!--box-title-->
          <div class="box-content">
                <p>
                    <?php if( $this->getIsSubscribed() ): ?>
                        <?php echo $this->__("You are currently subscribed to 'General Subscription'.") ?>
                    <?php else: ?>
                        <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
                    <?php endif; ?>
                </p>   
          </div>  <!--box-content-->                 
        <?php /* Extensions placeholder */ ?>
        <?php echo $this->getChildHtml('customer.account.dashboard.info.extra')?>
      </div>  <!--box-->
    </div>
    <?php endif; ?>
</div>
