<div class="add-to-box">
<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Update Cart'); ?>

<?php if($_product->isSaleable()): ?>      
        <?php if(!$_product->isGrouped()): ?>
<div class="add-to-cart">
      <label for="qty"><?php echo $this->__('Qty:') ?></label> 

 <span class="qty-input-text ">
            <select  name="qty" id="qty" >
                <?php
                   for ($x=1; $x<=50; $x=$x+1) {
                    echo '<option value="' . $x . '">' . $x . ' </option>';
                }
                ?>
            </select> 
       </span>
     
</div> <!--add-to-cart-->
        <?php endif; ?>        
        <?php echo $this->getChildHtml('', true, true) ?>        
             
<?php endif; ?>

<button type="button"  title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><?php echo $buttonTitle ?></span></button> 

<script type="text/javascript">
//<![CDATA[
jQuery(function($) {
$('.add-to-cart .button-up').click(function() {
$qty = $(this).parent().find('.qty');
qty = parseInt($qty.val()) + 1;
$qty.val(qty);
});
$('.add-to-cart .button-down').click(function() {
$qty = $(this).parent().find('.qty');
qty = parseInt($qty.val()) - 1;
if (qty < 0)
qty = 0;
$qty.val(qty);
});
});
//]]>
</script>

</div> <!--add-to-box-->