
    <div class="page-title">
        <h2><?php echo $this->getTitle() ?></h2>
    </div>
<div class="line"></div>
  <div class="page-sitemap">
    <div id="sitemap_top_links">
        <?php echo $this->getChildHtml('links') ?>
    </div>
    <?php echo $this->getChildHtml('pager_top') ?>
    <?php echo $this->getChildHtml('sitemap') ?>
    <?php echo $this->getChildHtml('links') ?>
    <?php echo $this->getChildHtml('pager_bottom') ?>
  </div> <!--page-sitemap-->