<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
    $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product);
?>


<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/cloud-zoom.js') ?>"></script>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div class="product-view">
    <form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="magik_quickview"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
    <div class="product-essential">
	
	  <?php echo $this->getChildHtml('media') ?>
	  <div class="product-shop">
	      <div class="product-name">
		  <h1>
		      <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
		      <?php echo $this->htmlEscape($_product->getName()); ?> </a>
		  </h1>
	      </div> 
	    <div class="short-description">
		<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
	    </div>
	    <?php if($_product->getRatingSummary()): ?>
		<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
	    <?php  endif;  ?> 
      
	    <?php echo $this->getChildHtml('product_type_data') ?>
            <?php echo $this->getTierPriceHtml() ?>
            <?php echo $this->getChildHtml('extrahint') ?>
            <?php if($_product->isSaleable()): ?>
                      <?php if($this->hasOptions()): ?>
                            <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                     <?php endif; ?>
            <?php endif; ?>



<div class="add-to-box">
            <?php if($_product->isSaleable()): ?>
                <?php if(!$_product->isGrouped()): ?>
                    <div class="add-to-cart">
      <label for="qty"><?php echo $this->__('Qty:') ?></label> 

 <span class="qty-input-text ">
            <select  name="qty" id="qty" >
                <?php
                
                for ($x=1; $x<=20; $x=$x+1) {
                    echo '<option value="' . $x . '">' . $x . ' </option>';
                }
                ?>
            </select> 
       </span>
     
</div> <!--add-to-cart-->
                <?php endif; ?>
                <button title="<?php echo $this->__('Add to Cart') ?>" type="button" class="button btn-cart"  onclick="productAddToCartForm.submit(this)"><span><?php echo $this->__('Add to Cart')?></span></button>
                <?php else: ?>
                      <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>
              </div> <!--add-to-box-->
	     
	     

	</div> <!--product-shop-->
  </div> <!--product-essential-->
</form>
<script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('magik_quickview');
        productAddToCartForm.submit = function(button, url) { 
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){ 
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
</div> <!--product-view-->

