
<?php if ($_products = $this->getRecentlyComparedProducts()): ?>
<div class="block block-list block-compared">
    <div class="block-title">
        <?php echo $this->__('Recently Compared') ?>
    </div>
    <div class="block-content">
        <ol id="recently-compared-items">
        <?php foreach ($_products as $_item): ?>
            <li class="item">

               <a class="product-name" href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName() , 'name') ?></a>
            </li>
        <?php endforeach; ?>
        </ol>
        <script type="text/javascript">decorateList('recently-compared-items');</script>
    </div>
</div>
<?php endif; ?>
