
<div class="box-collateral box-tags">
    <?php echo $this->getChildHtml('list_before')?>
    <?php if( $this->getCount() ): ?>
    <h3><?php echo $this->__('Other people marked this product with these tags:') ?></h3>
    <ul id="<?php echo $this->getUniqueHtmlId('product-tags_'); ?>" class="product-tags">
        <?php echo $this->renderTags('<li><a href="%1$s">%2$s</a> (%3$s)</li>') ?>
    </ul>
    <script type="text/javascript">
        decorateGeneric($("<?php echo $this->getUniqueHtmlId('product-tags_'); ?>").select('li'), ['first', 'last']);
    </script>
    <?php endif; ?>
<div class="tags">
    <form id="addTagForm" action="<?php echo $this->getFormAction(); ?>" method="get">
        <div class="form-add-tags">
            <label for="productTagName"><?php echo $this->__('Add Tags:') ?></label>
          <div class="input-box">
            <input style="width:360px;" type="text" class="input-text required-entry" name="productTagName" id="productTagName" />           
            <button type="button" title="<?php echo $this->__('Add Tags') ?>" class=" button btn-add" onclick="submitTagForm()">                
                    <span><?php echo $this->__('Add Tags') ?></span>            
            </button>
          </div> <!--input-box-->
        </div>
    </form>
</div> <!--tags-->
    <p class="note"><?php echo $this->__("Use spaces to separate tags. Use single quotes (') for phrases.") ?></p>
    <script type="text/javascript">
    //<![CDATA[
        var addTagFormJs = new VarienForm('addTagForm');
        function submitTagForm(){
            if(addTagFormJs.validator.validate()) {
                addTagFormJs.form.submit();
            }
        }
    //]]>
    </script>
</div>
