
<div class="block block-tags">
    <div class="block-title"> Popular Tags</div>
    <div class="block-content">
        <ul class="tags-list">
            <?php foreach ($this->getTags() as $_tag): ?>
                <li><a href="<?php echo $_tag->getTaggedProductsUrl() ?>" style="font-size:<?php echo $_tag->getRatio()*70+75 ?>%;"><?php echo $this->htmlEscape($_tag->getName()) ?></a></li>
            <?php endforeach; ?>
        </ul>
        <div class="actions">
            <a class="view-all" href="<?php echo $this->getUrl('tag/list') ?>"><?php echo $this->__('View All Tags') ?></a>
        </div>
    </div>
</div>
