<?php
/* @var $this Temando_Temando_Block_Onepage_Shipping_Method_Available_Single */
$_rates = $this->getTemandoShippingRates();
$_options = $this->getOptions();
$sole = $this->getSole();
?>

<?php foreach ($_rates as $_rate): ?>
    <dt style="margin-bottom: 5px;">

    <?php if ($_rate->getErrorMessage()): ?>
	<ul class="messages"><li class="error-msg"><ul><li><?php echo $_rate->getErrorMessage() ?></li></ul></li></ul>
    <?php else: ?>
	    <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>" class="validate-one-required-by-name <?php echo $this->getClassFromRateCode($_rate->getCode())?>"<?php if($sole) echo ' checked="checked"' ?>/>
	    <label for="s_method_<?php echo $_rate->getCode() ?>"><!--<b><?php echo $this->getCarrierName(Temando_Temando_Model_Hybrid::CARRIER_CODE) ?>:</b>--> <?php echo $_rate->getMethodTitle() ?>
	    <strong>
	    <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
	    <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>

	    <?php echo $_excl; ?>
	    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
		(<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
	    <?php endif; ?>
	    </strong>
	    </label>
    <?php endif ?>
    </dt>
<?php endforeach; ?>
<div id="temando_checkboxes">
    <br />
    <table class='insurance'>
	<tr>
	<?php foreach($_options as $_option_id => $_option): ?>
	    <?php /* @var $_option Temando_Temando_Model_Option_Abstract */ ?>
	    <?php if ($_option instanceof Temando_Temando_Model_Option_Boolean): ?>
		<?php if ($_option->getForcedValue() === Temando_Temando_Model_Option_Boolean::NO): ?>
		    <td class='c1' style="display: none;">
		<?php else : ?>
		    <td class='c1'>
		<?php endif; ?>
		    <input
			type="checkbox"
			<?php if ($_option->getForcedValue() !== Temando_Temando_Model_Option_Boolean::NO): ?>
			    checked="checked"
			<?php endif; ?>
			id="temando_checkbox_<?php echo $_option_id; ?>"
			<?php if ($_option->getForcedValue() === Temando_Temando_Model_Option_Boolean::YES): ?>
			    disabled="disabled"
			<?php endif; ?>
			class="checkbox"
		    />
		    <label for="temando_checkbox_<?php echo $_option_id; ?>">
			<?php echo $_option->getName(); ?>
		    </label>
	    <?php endif; ?>
		</td>
	<?php endforeach; ?>
	    </tr>
	    <tr>
	<?php foreach($this->getOptions() as $_option_id => $_option): ?>
	    <?php /* @var $_option Temando_Temando_Model_Option_Abstract */ ?>
	    <?php if ($_option instanceof Temando_Temando_Model_Option_Boolean): ?>
		<?php if ($_option->getForcedValue() === Temando_Temando_Model_Option_Boolean::NO): ?>
		    <td class='c2' style="display: none;">
		<?php else : ?>
		    <td class='c2'>
		<?php endif; ?>
		<?php echo $_option->getDescription(); ?>
	    <?php endif; ?>
		</td>
	<?php endforeach; ?>
	</tr>
    </table>
</div>
<script type="text/javascript">
//<![CDATA[
    $$('#temando_checkboxes input[type=checkbox]').each(function (control) {
	Event.observe(control, 'click', function () {
	    option_update_onestep(control);
	})
    });
    // Hide Temando quotes that don't match the checked options
    option_update_onestep();
//]]>
</script>