<?php

class Neev_SKUautogenerate_Block_Adminhtml_SKUautogenerate_Edit_Tab_Form extends Mage_Adminhtml_Block_Widget_Form
{
  protected function _prepareForm()
  {
      $form = new Varien_Data_Form();
      $this->setForm($form);
      $fieldset = $form->addFieldset('skuautogenerate_form', array('legend'=>Mage::helper('skuautogenerate')->__('Rule information')));
     
      
      $fieldset->addField('prependstring', 'text', array(
          'label'     => Mage::helper('skuautogenerate')->__('SKU prefix string'),
          //'class'     => 'required-entry',
          'required'  => false,
          'name'      => 'prependstring',
          'maxlength' => 3,
          'after_element_html' => '<small>Max length 3 chars (leave blank for no Prefix)</small>',

      ));

      $fieldset->addField('appendstring', 'text', array(
          'label'     => Mage::helper('skuautogenerate')->__('SKU suffix string'),
         // 'class'     => 'required-entry',
          'required'  => false,
          'name'      => 'appendstring',
          'maxlength' => 3,
          'after_element_html' => '<small>Max length 3 chars (leave blank for no Suffix) </small>',

      ));
       $fieldset->addField('stringfunction', 'select', array(
          'label'     => Mage::helper('skuautogenerate')->__('Set String to SKU'),
          'name'      => 'stringfunction',
          'values'    => array(
             array(
                  'value'     => 'both',
                  'label'     => Mage::helper('skuautogenerate')->__('Both'),
              ), 
              
              array(
                  'value'     => 'prefix',
                  'label'     => Mage::helper('skuautogenerate')->__('Prefix only'),
              ),
              array(
                  'value'     => 'suffix',
                  'label'     => Mage::helper('skuautogenerate')->__('Suffix only'),
              ),
          ),
          'after_element_html' => '<small><br/>Set Prefix, Suffix, Both</small>',

      ));
      $fieldset->addField('min_length', 'text', array(
          'label'     => Mage::helper('skuautogenerate')->__('Minimum lengh of sku'),
          'class'     => 'required-entry validate-digits',
          'required'  => true,
           'name'      => 'min_length',
          'maxlength' => 2,
          'value' =>10,
      'after_element_html' => '<small>Add numeric value only</small>',
            
            
      ));

        $fieldset->addField('product_type', 'select', array(
          'label'     => Mage::helper('skuautogenerate')->__('Product type'),
          'name'      => 'product_type',
          'values'    => array(
             array(
                  'value'     => 'unique',
                  'label'     => Mage::helper('skuautogenerate')->__('All Product Types'),
              ),
              array(
                  'value'     => 'simple',
                  'label'     => Mage::helper('skuautogenerate')->__('Simple'),
              ),
              array(
                  'value'     => 'configurable',
                  'label'     => Mage::helper('skuautogenerate')->__('Configurable'),
              ),
              array(
                  'value'     => 'bundle',
                  'label'     => Mage::helper('skuautogenerate')->__('Bundle'),
              ),
              array(
                  'value'     => 'grouped',
                  'label'     => Mage::helper('skuautogenerate')->__('Grouped'),
              ),
              array(
                  'value'     => 'downloadable',
                  'label'     => Mage::helper('skuautogenerate')->__('Downloadable'),
              ),
             array(
                  'value'     => 'virtual',
                  'label'     => Mage::helper('skuautogenerate')->__('Virtual'),
              ), 
          ),
          'after_element_html' => '<small><br/>Select Product Type for which this Rule applies.</small>',

      ));
     

    
      $fieldset->addField('status', 'select', array(
          'label'     => Mage::helper('skuautogenerate')->__('Status'),
          'name'      => 'status',
          'values'    => array(
              array(
                  'value'     => 1,
                  'label'     => Mage::helper('skuautogenerate')->__('Enabled'),
              ),

              array(
                  'value'     => 2,
                  'label'     => Mage::helper('skuautogenerate')->__('Disabled'),
              ),
          ),
      ));
     
        
      if ( Mage::getSingleton('adminhtml/session')->getSKUautogenerateData() )
      {
          $form->setValues(Mage::getSingleton('adminhtml/session')->getSKUautogenerateData());
          Mage::getSingleton('adminhtml/session')->setSKUautogenerateData(null);
      } elseif ( Mage::registry('skuautogenerate_data') ) {
          $form->setValues(Mage::registry('skuautogenerate_data')->getData());
      }
      return parent::_prepareForm();
  }
}