
<?php if(Mage::getModel('customer/session')->getUserRegister()):?>
   <script>
   <?
   $userId = Mage::getSingleton('customer/session')->getCustomer()->getId();
   $userEmail = Mage::getModel('customer/session')->getUserRegistered();
   ?>
   Conversions.userRegister('<?=$userId?>','<?=$userEmail?>');
   </script>
   <?php 
   Mage::getModel('customer/session')->unsUserRegister();
   ?>
<?php endif; ?>
<!-- MIDORI MMX -->
<?php if(Mage::getModel('customer/session')->getUserLogin()):?>
   <script>
   <?
   $userId = Mage::getSingleton('customer/session')->getCustomer()->getId();
   $userEmail = Mage::getModel('customer/session')->getUserLogin();
   ?>
   Conversions.userLogin('<?=$userId?>','<?=$userEmail?>');
   </script>
   <?php 
   Mage::getModel('customer/session')->unsUserLogin();
   ?>
<?php endif; ?>
<?php if(Mage::getModel('customer/session')->getAddProduct()):?>
   <script>
   Conversion.prototype.addToCart(<?=Mage::getModel('customer/session')->getAddProduct()?>);
   <?php 
   Mage::getModel('customer/session')->unsAddProduct();
   ?>
   </script>
<?php endif; ?>
<?php if(Mage::getModel('customer/session')->getRemoveProduct()):?>
   <script>
   Conversion.prototype.removeFromCart(<?=Mage::getModel('customer/session')->getAddProduct()?>);
   </script>
   <?php 
   Mage::getModel('customer/session')->unsRemoveProduct();
   ?>
<?php endif; ?>
<?php if(Mage::getModel('customer/session')->getProductView()):?>
   <script>
   Conversion.prototype.productView(<?=Mage::getModel('customer/session')->getProductView()?>);
   </script>
   <?php 
   Mage::getModel('customer/session')->unsProductView();
   ?>
<?php endif; ?>
<?php if(Mage::getModel('customer/session')->getProductList()):?>
   <?php foreach(Mage::getModel('customer/session')->getProductList() as $product):?>
   <script>
   var productsList = <?=json_encode($product)?>;
   var isCategory = '<?php
   if(Mage::registry('current_category')==null){
      echo "false";
   }
   
   ?>';
   if(isCategory == ''){
      productsList['list'] = 'katalog';
   }
   else{
      productsList['list'] = 'other';
   }  
   Conversion.prototype.productList(productsList);
   </script>
   <?php endforeach;?>
   <?php 
   Mage::getModel('customer/session')->unsProductList();
   ?>
<?php endif; ?>
<?php if(Mage::getModel('customer/session')->getPurchaseProduct()):?>
   <script>
      Conversions.purchaseProduct(<?=Mage::getModel('customer/session')->getPurchaseProduct()?>,<?=Mage::getModel('customer/session')->getPurchasedProducts()?>);
      
      var purchaseData = <?=Mage::getModel('customer/session')->getPurchaseProduct()?>;
      
   </script>
   <!-- Google Code for Sat&#305;&#351; Conversion Page -->
   <script type="text/javascript">
   /* <![CDATA[ */
   var google_conversion_id = 923549472;
   var google_conversion_language = "en";
   var google_conversion_format = "2";
   var google_conversion_color = "ffffff";
   var google_conversion_label = "JwZgCLqnmVkQoP6wuAM";
   var google_conversion_value = Number(purchaseData.revenue) + Number(purchaseData.shipping);
   var google_conversion_currency = "TRY";
   var google_remarketing_only = false;
   /* ]]> */
   </script>
   <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
   </script>
   <noscript>
   <div style="display:inline;">
   <img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/923549472/?value=1.00&amp;currency_code=TRY&amp;label=JwZgCLqnmVkQoP6wuAM&amp;guid=ON&amp;script=0"/>
   </div>
   </noscript>
   <?php 
   Mage::getModel('customer/session')->unsPurchaseProduct();
   Mage::getModel('customer/session')->unsPurchasedProducts();
   ?>
   <?php endif; ?>
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 923549472;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/923549472/?value=0&amp;guid=ON&amp;script=0"/>
</div>
</noscript>